### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by langston-barrett** [jwiegley/coq-haskell#1]
I'm interested in this library, but I can't seem to find much documentation! Is there any?

**Comment by jwiegley** [comment]
@siddharthist That's a great question, but no, there is no documentation.  It's been evolving purely on an "as needed" basis, and so I've not yet been motivated to sit down and document the parts that are there.

In general the principle is to follow the naming and structure of the Haskell standard libraries as closely as possible, so that the documentation you need could be found there.  The goal is for Coq programming to feel "familiar" to a Haskell programmer, and also to ease direct translation of Haskell programs into Coq, and vice-versa (since I use Coq as a way of proving properties about Haskell algorithms and data structures).

For example, you can `Require Import Hask.Control.Monad.Free`, and have many of the same facilities available to you as might be found in `Control.Monad.Free` from @ekmett 's `free` package.  It also requires the term algebra to be a `Functor`, just like Haskell would, and all the operations and nomenclature relating to Functors should feel right at home.

If there are particular uses you have in mind, or certain questions, I can answer them here and we could start building up some documentation that way.

**Comment by langston-barrett** [comment]
@jwiegley Thanks so much for the great explanation!
